name: Deploy backend to Azure app service

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Build project
        run: mvn clean install -f infratrack_userportal-backend/pom.xml
      - name: Upload Artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: infratrack-backend
          path: ${{github.workspace}}/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: infratrack-backend
      - name: Deploy to azure app service
        uses: azure/webapps-deploy@v2
        with:
          app-name: infratrack-backend
          publish-profile: ${{secrets.azureWebAppPublishProfile}}
          package: "*.jar"
